version: '3.8'

services:
  web:
    build: .
    command: gunicorn mobtakir_website_django.wsgi:application --bind 0.0.0.0:8000 --workers 4 --threads 2
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
      - sqlite_data:/app/data
    ports:
      - "8094:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=mobtakir_website_django.settings
      - OLLAMA_HOST=http://ollama:11434
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CACHE_MIDDLEWARE_SECONDS=604800
      - WHITENOISE_MAX_AGE=604800
    depends_on:
      - ollama
      - redis
    restart: always

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: always

  ollama:
    image: ollama/ollama:latest
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"

volumes:
  static_volume:
  media_volume:
  ollama_data:
  sqlite_data:
  redis_data: