# Generated by Django 5.1 on 2024-12-05 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_chatmessage_error_message_chatmessage_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='api_key',
            field=models.CharField(blank=True, default='AIzaSyAwdxQfnpVrMaExufEk4A4JPEWl6hTyaQE', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='auto_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='context_memory',
            field=models.IntegerField(default=5, max_length=20),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='endpoint_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='language',
            field=models.CharField(choices=[('english', 'english'), ('arabic', 'arabic'), ('french', 'french')], default='english', max_length=10),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='max_tokens',
            field=models.IntegerField(default=1050, max_length=2000),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='temperature',
            field=models.DecimalField(decimal_places=1, default=0.7, max_digits=2),
        ),
    ]
