# Generated by Django 5.1 on 2024-12-05 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_chatsession_api_key_chatsession_auto_correct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsession',
            name='context_memory',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='max_tokens',
            field=models.IntegerField(default=1050),
        ),
    ]
