# Generated by Django 4.2.7 on 2024-12-18 00:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('negative_prompt', models.TextField(blank=True, null=True)),
                ('audio_length', models.FloatField(default=5.0)),
                ('guidance_scale', models.FloatField(default=2.5)),
                ('num_inference_steps', models.IntegerField(default=10)),
                ('audio_file', models.FileField(upload_to='generated_audio/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
